export default [
    { "id": 1, "text": "The greatest glory in living lies not in never falling, but in rising every time we fall.", "author": "Nelson Mandela" },
    { "id": 2, "text": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney" },
    { "id": 3, "text": "Your time is limited, so don't waste it living someone else's life.", "author": "Steve Jobs" },
    { "id": 4, "text": "If life were predictable it would cease to be life, and be without flavor.", "author": "Eleanor Roosevelt" },
    { "id": 5, "text": "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", "author": "Oprah Winfrey" },
    { "id": 6, "text": "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", "author": "James Cameron" },
    { "id": 7, "text": "Life is what happens when you're busy making other plans.", "author": "John Lennon" },
    { "id": 8, "text": "Spread love everywhere you go. Let no one ever come to you without leaving happier.", "author": "Mother Teresa" },
    { "id": 9, "text": "When you reach the end of your rope, tie a knot in it and hang on.", "author": "Franklin D. Roosevelt" },
    { "id": 10, "text": "Always remember that you are absolutely unique. Just like everyone else.", "author": "Margaret Mead" },
    { "id": 11, "text": "Don't judge each day by the harvest you reap but by the seeds that you plant.", "author": "Robert Louis Stevenson" },
    { "id": 12, "text": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt" },
    { "id": 13, "text": "Tell me and I forget. Teach me and I remember. Involve me and I learn.", "author": "Benjamin Franklin" },
    { "id": 14, "text": "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", "author": "Helen Keller" },
    { "id": 15, "text": "It is during our darkest moments that we must focus to see the light.", "author": "Aristotle" },
    { "id": 16, "text": "Whoever is happy will make others happy too.", "author": "Anne Frank" },
    { "id": 17, "text": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson" },
    { "id": 18, "text": "You will face many defeats in life, but never let yourself be defeated.", "author": "Maya Angelou" },
    { "id": 19, "text": "The greatest glory in living lies not in never falling, but in rising every time we fall.", "author": "Nelson Mandela" },
    { "id": 20, "text": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney" },
    { "id": 21, "text": "Your time is limited, so don't waste it living someone else's life.", "author": "Steve Jobs" },
    { "id": 22, "text": "If life were predictable it would cease to be life, and be without flavor.", "author": "Eleanor Roosevelt" },
    { "id": 23, "text": "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", "author": "Oprah Winfrey" },
    { "id": 24, "text": "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", "author": "James Cameron" },
    { "id": 25, "text": "Life is what happens when you're busy making other plans.", "author": "John Lennon" },
    { "id": 26, "text": "Spread love everywhere you go. Let no one ever come to you without leaving happier.", "author": "Mother Teresa" },
    { "id": 27, "text": "When you reach the end of your rope, tie a knot in it and hang on.", "author": "Franklin D. Roosevelt" },
    { "id": 28, "text": "Always remember that you are absolutely unique. Just like everyone else.", "author": "Margaret Mead" },
    { "id": 29, "text": "Don't judge each day by the harvest you reap but by the seeds that you plant.", "author": "Robert Louis Stevenson" },
    { "id": 30, "text": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt" },
    { "id": 31, "text": "Tell me and I forget. Teach me and I remember. Involve me and I learn.", "author": "Benjamin Franklin" },
    { "id": 32, "text": "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", "author": "Helen Keller" },
    { "id": 33, "text": "It is during our darkest moments that we must focus to see the light.", "author": "Aristotle" },
    { "id": 34, "text": "Whoever is happy will make others happy too.", "author": "Anne Frank" },
    { "id": 35, "text": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson" },
    { "id": 36, "text": "You will face many defeats in life, but never let yourself be defeated.", "author": "Maya Angelou" },
    { "id": 37, "text": "The greatest glory in living lies not in never falling, but in rising every time we fall.", "author": "Nelson Mandela" },
    { "id": 38, "text": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney" },
    { "id": 39, "text": "Your time is limited, so don't waste it living someone else's life.", "author": "Steve Jobs" },
    { "id": 40, "text": "If life were predictable it would cease to be life, and be without flavor.", "author": "Eleanor Roosevelt" },
    { "id": 41, "text": "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", "author": "Oprah Winfrey" },
    { "id": 42, "text": "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", "author": "James Cameron" },
    { "id": 43, "text": "Life is what happens when you're busy making other plans.", "author": "John Lennon" },
    { "id": 44, "text": "Spread love everywhere you go. Let no one ever come to you without leaving happier.", "author": "Mother Teresa" },
    { "id": 45, "text": "When you reach the end of your rope, tie a knot in it and hang on.", "author": "Franklin D. Roosevelt" },
    { "id": 46, "text": "Always remember that you are absolutely unique. Just like everyone else.", "author": "Margaret Mead" },
    { "id": 47, "text": "Don't judge each day by the harvest you reap but by the seeds that you plant.", "author": "Robert Louis Stevenson" },
    { "id": 48, "text": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt" },
    { "id": 49, "text": "Tell me and I forget. Teach me and I remember. Involve me and I learn.", "author": "Benjamin Franklin" },
    { "id": 50, "text": "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", "author": "Helen Keller" },
    { "id": 51, "text": "It is during our darkest moments that we must focus to see the light.", "author": "Aristotle" },
    { "id": 52, "text": "Whoever is happy will make others happy too.", "author": "Anne Frank" },
    { "id": 53, "text": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson" },
    { "id": 54, "text": "You will face many defeats in life, but never let yourself be defeated.", "author": "Maya Angelou" },
    { "id": 55, "text": "The greatest glory in living lies not in never falling, but in rising every time we fall.", "author": "Nelson Mandela" },
    { "id": 56, "text": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney" },
    { "id": 57, "text": "Your time is limited, so don't waste it living someone else's life.", "author": "Steve Jobs" },
    { "id": 58, "text": "If life were predictable it would cease to be life, and be without flavor.", "author": "Eleanor Roosevelt" },
    { "id": 59, "text": "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", "author": "Oprah Winfrey" },
    { "id": 60, "text": "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", "author": "James Cameron" },
    { "id": 61, "text": "Life is what happens when you're busy making other plans.", "author": "John Lennon" },
    { "id": 62, "text": "Spread love everywhere you go. Let no one ever come to you without leaving happier.", "author": "Mother Teresa" },
    { "id": 63, "text": "When you reach the end of your rope, tie a knot in it and hang on.", "author": "Franklin D. Roosevelt" },
    { "id": 64, "text": "Always remember that you are absolutely unique. Just like everyone else.", "author": "Margaret Mead" },
    { "id": 65, "text": "Don't judge each day by the harvest you reap but by the seeds that you plant.", "author": "Robert Louis Stevenson" },
    { "id": 66, "text": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt" },
    { "id": 67, "text": "Tell me and I forget. Teach me and I remember. Involve me and I learn.", "author": "Benjamin Franklin" },
    { "id": 68, "text": "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", "author": "Helen Keller" },
    { "id": 69, "text": "It is during our darkest moments that we must focus to see the light.", "author": "Aristotle" },
    { "id": 70, "text": "Whoever is happy will make others happy too.", "author": "Anne Frank" },
    { "id": 71, "text": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson" },
    { "id": 72, "text": "You will face many defeats in life, but never let yourself be defeated.", "author": "Maya Angelou" },
    { "id": 73, "text": "The greatest glory in living lies not in never falling, but in rising every time we fall.", "author": "Nelson Mandela" },
    { "id": 74, "text": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney" },
    { "id": 75, "text": "Your time is limited, so don't waste it living someone else's life.", "author": "Steve Jobs" },
    { "id": 76, "text": "If life were predictable it would cease to be life, and be without flavor.", "author": "Eleanor Roosevelt" },
    { "id": 77, "text": "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", "author": "Oprah Winfrey" },
    { "id": 78, "text": "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", "author": "James Cameron" },
    { "id": 79, "text": "Life is what happens when you're busy making other plans.", "author": "John Lennon" },
    { "id": 80, "text": "Spread love everywhere you go. Let no one ever come to you without leaving happier.", "author": "Mother Teresa" },
    { "id": 81, "text": "When you reach the end of your rope, tie a knot in it and hang on.", "author": "Franklin D. Roosevelt" },
    { "id": 82, "text": "Always remember that you are absolutely unique. Just like everyone else.", "author": "Margaret Mead" },
    { "id": 83, "text": "Don't judge each day by the harvest you reap but by the seeds that you plant.", "author": "Robert Louis Stevenson" },
    { "id": 84, "text": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt" },
    { "id": 85, "text": "Tell me and I forget. Teach me and I remember. Involve me and I learn.", "author": "Benjamin Franklin" },
    { "id": 86, "text": "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", "author": "Helen Keller" },
    { "id": 87, "text": "It is during our darkest moments that we must focus to see the light.", "author": "Aristotle" },
    { "id": 88, "text": "Whoever is happy will make others happy too.", "author": "Anne Frank" },
    { "id": 89, "text": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson" },
    { "id": 90, "text": "You will face many defeats in life, but never let yourself be defeated.", "author": "Maya Angelou" },
    { "id": 91, "text": "The greatest glory in living lies not in never falling, but in rising every time we fall.", "author": "Nelson Mandela" },
    { "id": 92, "text": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney" },
    { "id": 93, "text": "Your time is limited, so don't waste it living someone else's life.", "author": "Steve Jobs" },
    { "id": 94, "text": "If life were predictable it would cease to be life, and be without flavor.", "author": "Eleanor Roosevelt" },
    { "id": 95, "text": "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", "author": "Oprah Winfrey" },
    { "id": 96, "text": "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", "author": "James Cameron" },
    { "id": 97, "text": "Life is what happens when you're busy making other plans.", "author": "John Lennon" },
    { "id": 98, "text": "Spread love everywhere you go. Let no one ever come to you without leaving happier.", "author": "Mother Teresa" },
    { "id": 99, "text": "When you reach the end of your rope, tie a knot in it and hang on.", "author": "Franklin D. Roosevelt" },
    { "id": 100, "text": "Always remember that you are absolutely unique. Just like everyone else.", "author": "Margaret Mead" }
  ]
  